# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-helper" do
  name "mcp-helper"
  desc "CLI tool for managing MCP (Model Context Protocol) server configurations"
  homepage "https://github.com/stephenwilliams/mcp-helper"
  version "1.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-helper"
  bash_completion "completions/mcp-helper.bash"
  zsh_completion "completions/mcp-helper.zsh"
  fish_completion "completions/mcp-helper.fish"

  on_macos do
    on_intel do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_darwin_amd64.tar.gz"
      sha256 "fb30d257c3dae5fa941fca167528e49be9a285aa443d1da63a9b31a1d2101bd0"
    end
    on_arm do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_darwin_arm64.tar.gz"
      sha256 "19d017b627740375c62bc18814c28c9b5b191e4105fef32c60416857aff53021"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_linux_amd64.tar.gz"
      sha256 "058cc55172136361d8c070727a365dcddad924f3cbb93f72931bf3a2f94a151d"
    end
    on_arm do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_linux_arm64.tar.gz"
      sha256 "57e672c562760b692a6d9ac63a391d1bd28ab46cd2bca224a08ffdec00090511"
    end
  end

  # No zap stanza required
end
