# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-helper" do
  name "mcp-helper"
  desc "CLI tool for managing MCP (Model Context Protocol) server configurations"
  homepage "https://github.com/stephenwilliams/mcp-helper"
  version "0.3.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-helper"
  bash_completion "completions/mcp-helper.bash"
  zsh_completion "completions/mcp-helper.zsh"
  fish_completion "completions/mcp-helper.fish"

  on_macos do
    on_intel do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_darwin_amd64.tar.gz"
      sha256 "11ab4818744921a112875b9c4d88d03198cfc7039b4f933c135ee3fe4f671488"
    end
    on_arm do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_darwin_arm64.tar.gz"
      sha256 "db9fc91e48d3fddb65bbd3a439f7eff397e2a4c4c1667782ba3db7265d2cad1a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_linux_amd64.tar.gz"
      sha256 "f3f425efaa90dad199f5e7034c5eec8a7703b2acd6bb301e7bb214b775d8168b"
    end
    on_arm do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_linux_arm64.tar.gz"
      sha256 "9f1535f19bc1bad5ff20fbbc2e6f4894ed7d73ceed13fe45e32bf487452dc7e1"
    end
  end

  # No zap stanza required
end
