# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-helper" do
  name "mcp-helper"
  desc "CLI tool for managing MCP (Model Context Protocol) server configurations"
  homepage "https://github.com/stephenwilliams/mcp-helper"
  version "0.3.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-helper"
  bash_completion "completions/mcp-helper.bash"
  zsh_completion "completions/mcp-helper.zsh"
  fish_completion "completions/mcp-helper.fish"

  on_macos do
    on_intel do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_darwin_amd64.tar.gz"
      sha256 "80846e6e29b0e00ce848702b9ccf729e848203201f68815e14ae8a1cb0e9e0d5"
    end
    on_arm do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_darwin_arm64.tar.gz"
      sha256 "a25606a9c3a380e7cb67f4ae589b005ac862ed7e2fdf7b405fb8f9cec8205da2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_linux_amd64.tar.gz"
      sha256 "083fac61ccc24052aab3cf06d6ca487109fed19fa28d03d04608ece9975804c9"
    end
    on_arm do
      url "https://github.com/stephenwilliams/mcp-helper/releases/download/v#{version}/mcp-helper_#{version}_linux_arm64.tar.gz"
      sha256 "bf005f8aded166917295964d4d7325cb447a0ce6bcc31e4d34ece35e3b46b0ca"
    end
  end

  # No zap stanza required
end
