# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SemverCli < Formula
  desc ""
  homepage ""
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/stephenwilliams/semver-cli/releases/download/v0.1.0/semver-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "824c2594d62edd28932398abdb3099588a3384b7cab7d92e3dd81c308f0cb668"

      def install
        bin.install "semver-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stephenwilliams/semver-cli/releases/download/v0.1.0/semver-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "ba545903dc6c9cb8bfc18015c8b1ecf058680c38bbdc4f4b4dbe1ec6338648c4"

      def install
        bin.install "semver-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stephenwilliams/semver-cli/releases/download/v0.1.0/semver-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "748b2bcbc232b27d4579e3d155cc658899909f8e1f24d536ea800a8c5aeb1e30"

      def install
        bin.install "semver-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stephenwilliams/semver-cli/releases/download/v0.1.0/semver-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "6d6cf9b5419f594387352983b3e00e874faee2a034996c3cfb5be072d2bf02a1"

      def install
        bin.install "semver-cli"
      end
    end
  end
end
